### ISSUE TITLE
October Simulation Campaign Geometry Readiness

### ISSUE THREAD

**Issue by osbornjd** [eic/epic#176]
# October Readiness Overview

This issue is intended to track the outstanding geometry issues that need to be solved or addressed prior to the October simulation campaign. Discussion and/or issues and/or PRs can be explicitly linked here.

# Issues and Associated PRs
### pfRICH
- [x] Overlaps with tracking support addressed by  [158](https://github.com/eic/epic/pull/158), [issue 159](https://github.com/eic/epic/issues/159)

### mRICH
- [x] Updates of mRICH positioning [148](https://github.com/eic/epic/pull/148)

### EEcal
- [x] EECal updates addressed by [141](https://github.com/eic/epic/pull/141)

### TOF
- [x]  Add TOF to tracking [155](https://github.com/eic/epic/pull/155) and issue [154](https://github.com/eic/epic/issues/154)

### TOF
- [x] Length of barrel TOF inconsistent with menagerie
### Tracking (silicon, MPGDs)
- [x] #177
- [x] Inconsistency with menagerie [174](https://github.com/eic/epic/pull/174)

### DIRC
- [x] Update DIRC positioning [122](https://github.com/eic/epic/pull/122)

### ECals (SciGlass, Imaging)
- [x] #45
- [x] #179
- [x] #180
- [ ] Imaging ECal fiber cladding [172](https://github.com/eic/epic/pull/172). Leave it out for now due to slow down of simulation
- [x] Imaging offset in z inconsistent with menagerie [152](https://github.com/eic/epic/issues/152)

### HCal
- [x] sPHENIX HCal implementation [117](https://github.com/eic/epic/pull/117)

### Solenoid
- [x] New field map [164](https://github.com/eic/epic/pull/164)
- [x] -10 cm offset needs introduced [201](https://github.com/eic/epic/issues/201)

### dRICH
- [x] Confirm with menagerie that envelopes match [173](https://github.com/eic/epic/pull/173)

### FECal and insert
- [x] Implement insert geometry [156](https://github.com/eic/epic/pull/156)
- [x] Differences in menagerie [Issue 165](https://github.com/eic/epic/issues/165)

**Comment by rymilton** [comment]
Forward HCal and forward HCal insert are both implemented ([65](https://github.com/eic/epic/pull/65) & [153](https://github.com/eic/epic/pull/153)).

**Comment by wdconinc** [comment]
See also https://github.com/eic/epic/milestone/1.

**Comment by osbornjd** [comment]
Here is a list of outstanding PRs that need input from GD/I:
https://github.com/eic/epic/pull/174
https://github.com/eic/epic/pull/173
https://github.com/eic/epic/pull/158
https://github.com/eic/epic/pull/148
Others @wdconinc @sly2j ?
